### ISSUE TITLE
Hi Bhuvan!

### ISSUE THREAD

**Issue by mtorpey** [BhuvanBezawada/CS5099-Project#2]
Hi @BhuvanBezawada!

Long time no see!  Hoping you're well.  I just wanted to get in touch to let you know about the feedback helper and how useful it's been to a number of us in the School since you left!

I tried sending you an email a month or so ago, but of course I only have your old uni email so I wasn't expecting it to come through.  There's nothing urgent, but I thought you might be interested to hear about what's been going on.  If you'd like to hear what's been going on, do send me an email at mct25@st-andrews.ac.uk -- it'd be nice to catch up.

Cheers!

**Comment by BhuvanBezawada** [comment]
Hi Dr Young, 

Great to hear from you! 

I'm alright, thank you. Hope you're doing well too!

I would definitely be interested in hearing how the project has developed. 
I'll send you an email and we can catch up over there.

Thanks,
Bhuvan

**Edit:** Just sent you an email from my Gmail account.
